# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-03-28 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontPage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location',
            new_name='Location',
        ),
    ]
