# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-03-29 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontPage', '0002_auto_20200328_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_activity',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user_activity',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
