# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-03-31 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontPage', '0003_auto_20200329_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_activity',
            options={'ordering': ['FullName']},
        ),
    ]
